[workspace]
resolver = '2'
members = [
	'tasks/query_generator',
]

[workspace.dependencies]
anki = { path = "./anki/rslib" }
anki_proto = { path = "./anki/rslib/proto" }
anki_proto_gen = { path = "./anki/rslib/proto_gen" }
prost = '0.13'
