[package]
name = "query_generator"
version = "0.1.0"
edition = "2021"


[dependencies]
anki_proto_gen = {workspace = true}


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
