[package]
name = "anki-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anki = { path = "../../anki/rslib", features = ["rustls"] }
anki_proto = { path = "../../anki/rslib/proto" }
prost = { version = "0.13.5" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
